name: Check npm access

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML, so you have to quote this string
    # daily at 2:2
    - cron:  '22 2 * * *'

jobs:
  check-npms:
    name: check npm access
    if: |
      github.repository == 'ioBroker/ioBroker.repositories'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm i
      - run: npm run checkNpm
        env:
          OWN_GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }}
