name: Check ready for stable

on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    # every day
    - cron:  '33 3 * * *'

jobs:
  ready-for-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run stable
        env:
          OWN_GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }}
